name: Bug Report
description: Create a report to help us improve
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true

  - type: textarea
    id: css-example
    attributes:
      label: CSS Example
      description: Please provide the CSS code that demonstrates the issue
      placeholder: |
        ```css
        .example {
          color: if(media(min-width: 768px): blue; else: red);
        }
        ```
    validations:
      required: false

  - type: dropdown
    id: browsers
    attributes:
      label: Browsers Affected
      description: Which browsers are affected by this issue?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Internet Explorer
        - Other (please specify in additional context)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Package Version
      description: What version of css-if-polyfill are you using?
      placeholder: "1.0.0"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide information about your environment
      placeholder: |
        - OS: [e.g. macOS 12.0, Windows 10]
        - Browser: [e.g. Chrome 91, Firefox 89]
        - Node.js version: [e.g. 16.0.0]
        - Build tool: [e.g. Webpack, Vite, None]

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, including screenshots if applicable.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched the existing issues to make sure this is not a duplicate
          required: true
        - label: I have provided a minimal reproduction case
          required: false
        - label: I have tested this with the latest version of the package
          required: true
