name: Feature Request
description: Suggest an idea for this project
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: css-example
    attributes:
      label: CSS Example
      description: Please provide an example of how this feature would be used in CSS
      placeholder: |
        ```css
        .example {
          /* New feature usage example */
          property: if(new-condition-type(...): value; else: fallback);
        }
        ```
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
    validations:
      required: false

  - type: dropdown
    id: impact
    attributes:
      label: Impact Level
      description: How would you rate the impact of this feature?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Essential for my use case
        - Critical - Blocking my project
    validations:
      required: true

  - type: checkboxes
    id: breaking-change
    attributes:
      label: Breaking Change
      description: Would this feature require breaking changes?
      options:
        - label: This feature would require breaking changes to existing API
        - label: This feature could be implemented without breaking changes

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases where this feature would be beneficial
      placeholder: |
        1. Use case 1: [description]
        2. Use case 2: [description]
        3. Use case 3: [description]
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, mockups, or examples about the feature request here.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched the existing issues to make sure this is not a duplicate
          required: true
        - label: I have reviewed the project roadmap and this feature is not already planned
          required: false
        - label: I would be willing to contribute to implementing this feature
          required: false
